In [6]:
import pandas as pd
import numpy as np

In [7]:
df_index = pd.read_excel(r'C:\Users\12369\OneDrive\Desktop\mahdi\datascience\kourosh\project5\sp_index.xlsx' , header = 1).iloc[:,1:].sort_index(axis = 0 , ascending = False).reset_index().iloc[:,1:]
df_index.head()

        Date   Value
0 2021-10-31  0.0691
1 2021-11-30 -0.0083
2 2021-12-31  0.0436
3 2022-01-31 -0.0526
4 2022-02-28 -0.0314

In [8]:
df_index.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    50 non-null     datetime64[ns]
 1   Value   50 non-null     float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 932.0 bytes

In [9]:
df_index.loc[2,'Date']

Timestamp('2021-12-31 00:00:00')

In [10]:
df_factor = pd.read_csv(r'C:\Users\12369\OneDrive\Desktop\mahdi\datascience\kourosh\project5\[usa]_[all_factors]_[monthly]_[ew].csv')
df_factor

,location,name,freq,weighting,direction,n_stocks,n_stocks_min,date,ret
0,usa,age,monthly,ew,-1,502,8,1926-03-31,-0.066167
1,usa,age,monthly,ew,-1,505,12,1926-04-30,0.010546
2,usa,age,monthly,ew,-1,510,17,1926-05-31,-0.020292
3,usa,age,monthly,ew,-1,512,21,1926-06-30,-0.008927
4,usa,age,monthly,ew,-1,503,23,1926-07-31,0.017724
...,...,...,...,...,...,...,...,...,...
144615,usa,zero_trades_252d,monthly,ew,1,3627,1622,2024-08-31,0.052307
144616,usa,zero_trades_252d,monthly,ew,1,3631,1630,2024-09-30,0.003619
144617,usa,zero_trades_252d,monthly,ew,1,3614,1634,2024-10-31,0.005778
144618,usa,zero_trades_252d,monthly,ew,1,3595,1650,2024-11-30,-0.026987
144619,usa,zero_trades_252d,monthly,ew,1,3581,1677,2024-12-31,-0.045289

In [11]:
df_factor1= df_factor[['name','date' , 'ret']]
df_factor1

                    name        date       ret
0                    age  1926-03-31 -0.066167
1                    age  1926-04-30  0.010546
2                    age  1926-05-31 -0.020292
3                    age  1926-06-30 -0.008927
4                    age  1926-07-31  0.017724
...                  ...         ...       ...
144615  zero_trades_252d  2024-08-31  0.052307
144616  zero_trades_252d  2024-09-30  0.003619
144617  zero_trades_252d  2024-10-31  0.005778
144618  zero_trades_252d  2024-11-30 -0.026987
144619  zero_trades_252d  2024-12-31 -0.045289

[144620 rows x 3 columns]

In [12]:
df_factor1.tail()

                    name        date       ret
144615  zero_trades_252d  2024-08-31  0.052307
144616  zero_trades_252d  2024-09-30  0.003619
144617  zero_trades_252d  2024-10-31  0.005778
144618  zero_trades_252d  2024-11-30 -0.026987
144619  zero_trades_252d  2024-12-31 -0.045289

In [13]:
list_factor =list(df_factor1['name'].value_counts().index[:10])
print(list_factor)

['market_equity', 'prc', 'rmax1_21d', 'bidaskhl_21d', 'rmax5_21d', 'coskew_21d', 'ivol_capm_21d', 'ret_1_0', 'beta_dimson_21d', 'iskew_capm_21d']

In [14]:
df_factor2 = df_factor1[df_factor1['name'].isin(list_factor)]
df_factor2

                   name        date       ret
10583   beta_dimson_21d  1926-02-28  0.018624
10584   beta_dimson_21d  1926-03-31  0.044713
10585   beta_dimson_21d  1926-04-30 -0.020006
10586   beta_dimson_21d  1926-05-31  0.008904
10587   beta_dimson_21d  1926-06-30 -0.008320
...                 ...         ...       ...
113636        rmax5_21d  2024-08-31  0.071045
113637        rmax5_21d  2024-09-30  0.011152
113638        rmax5_21d  2024-10-31 -0.019015
113639        rmax5_21d  2024-11-30 -0.037675
113640        rmax5_21d  2024-12-31 -0.060737

[11872 rows x 3 columns]

In [15]:
list_year = df_index['Date'].apply(lambda x: x.year)

In [16]:
a= df_factor2['date'].apply(lambda x: int(x[:4]) ).isin(list_year)
df_factor3= df_factor2[a]
df_factor3

                   name        date       ret
11722   beta_dimson_21d  2021-01-31  0.013500
11723   beta_dimson_21d  2021-02-28 -0.046603
11724   beta_dimson_21d  2021-03-31  0.043301
11725   beta_dimson_21d  2021-04-30  0.032717
11726   beta_dimson_21d  2021-05-31 -0.000435
...                 ...         ...       ...
113636        rmax5_21d  2024-08-31  0.071045
113637        rmax5_21d  2024-09-30  0.011152
113638        rmax5_21d  2024-10-31 -0.019015
113639        rmax5_21d  2024-11-30 -0.037675
113640        rmax5_21d  2024-12-31 -0.060737

[480 rows x 3 columns]

In [17]:
df_factor3['new_date']=df_factor3['date'].str[:7]
df_factor3

C:\Users\12369\AppData\Local\Temp\ipykernel_28280\3696694778.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_factor3['new_date']=df_factor3['date'].str[:7]

                   name        date       ret new_date
11722   beta_dimson_21d  2021-01-31  0.013500  2021-01
11723   beta_dimson_21d  2021-02-28 -0.046603  2021-02
11724   beta_dimson_21d  2021-03-31  0.043301  2021-03
11725   beta_dimson_21d  2021-04-30  0.032717  2021-04
11726   beta_dimson_21d  2021-05-31 -0.000435  2021-05
...                 ...         ...       ...      ...
113636        rmax5_21d  2024-08-31  0.071045  2024-08
113637        rmax5_21d  2024-09-30  0.011152  2024-09
113638        rmax5_21d  2024-10-31 -0.019015  2024-10
113639        rmax5_21d  2024-11-30 -0.037675  2024-11
113640        rmax5_21d  2024-12-31 -0.060737  2024-12

[480 rows x 4 columns]

In [18]:
b= df_index['Date'].apply(lambda x:str(x).replace('_','/')[:7])
df_index['value_date'] =b
df_index.head()

        Date   Value value_date
0 2021-10-31  0.0691    2021-10
1 2021-11-30 -0.0083    2021-11
2 2021-12-31  0.0436    2021-12
3 2022-01-31 -0.0526    2022-01
4 2022-02-28 -0.0314    2022-02

In [19]:
 n =1
list_factor[n]

'prc'

In [20]:
df_factor4 = df_factor3[df_factor3['name']==list_factor[n]]
df_factor4.head()

      name        date       ret new_date
93792  prc  2021-01-31  0.167162  2021-01
93793  prc  2021-02-28  0.064537  2021-02
93794  prc  2021-03-31 -0.012375  2021-03
93795  prc  2021-04-30 -0.044954  2021-04
93796  prc  2021-05-31  0.017094  2021-05

In [21]:
data_merge =pd.merge(df_index , df_factor4 , left_on = 'value_date' , right_on ='new_date' , how = 'inner')

In [22]:
data_merge2=data_merge.rename(columns={'Value':'index_return' , 'ret':'factor_return' , 'new_date':'year-month' , 'name':'factor_name'})

In [23]:
df_factor5 = data_merge2[['factor_name' , 'year-month' , 'index_return' , 'factor_return']]
df_factor5.head()

  factor_name year-month  index_return  factor_return
0         prc    2021-10        0.0691      -0.042798
1         prc    2021-11       -0.0083      -0.032761
2         prc    2021-12        0.0436      -0.076937
3         prc    2022-01       -0.0526      -0.002518
4         prc    2022-02       -0.0314       0.002783

In [24]:
final1=df_factor5

In [25]:
np.corrcoef(final1['index_return'] , final1['factor_return'])[0,1]

np.float64(-0.11620119368511587)

In [26]:
import statsmodels.api as sm

In [27]:
final1['intercept']=1
final1.head()

C:\Users\12369\AppData\Local\Temp\ipykernel_28280\20640572.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final1['intercept']=1

  factor_name year-month  index_return  factor_return  intercept
0         prc    2021-10        0.0691      -0.042798          1
1         prc    2021-11       -0.0083      -0.032761          1
2         prc    2021-12        0.0436      -0.076937          1
3         prc    2022-01       -0.0526      -0.002518          1
4         prc    2022-02       -0.0314       0.002783          1

In [33]:
lm = sm.OLS(final1['index_return'] ,final1[['factor_return' , 'intercept']])
lm.fit().summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:           index_return   R-squared:                       0.014
Model:                            OLS   Adj. R-squared:                 -0.013
Method:                 Least Squares   F-statistic:                    0.5064
Date:                Wed, 10 Dec 2025   Prob (F-statistic):              0.481
Time:                        11:53:40   Log-Likelihood:                 62.640
No. Observations:                  39   AIC:                            -121.3
Df Residuals:                      37   BIC:                            -118.0
Df Model:                           1
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
factor_return    -0.1462      0.205     -0.712      0.481      -0.562       0.270
intercept         0.0070      0.009      0.820      0.417      -0.010       0.024
==============================================================================
Omnibus:                        1.812   Durbin-Watson:                   2.426
Prob(Omnibus):                  0.404   Jarque-Bera (JB):                1.576
Skew:                          -0.357   Prob(JB):                        0.455
Kurtosis:                       2.322   Cond. No.                         25.7
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [38]:
total_return = {}
for i in list_factor:
    df1 = df_factor3[df_factor3['name']==i]
    df2= pd.merge(df_index , df1 , left_on = 'value_date' , right_on ='new_date' , how = 'inner')
    total_return[i]=np.corrcoef(df2['ret'],df2['Value'])[0,1]

In [45]:
{i:float(j*100) for i,j in total_return.items()}

{'market_equity': -17.405155470600157,
 'prc': -11.620119368511588,
 'rmax1_21d': -51.50958271796255,
 'bidaskhl_21d': 49.04266306135249,
 'rmax5_21d': -53.159377039367186,
 'coskew_21d': -24.87344018073969,
 'ivol_capm_21d': -49.021270465810545,
 'ret_1_0': 31.49815156638217,
 'beta_dimson_21d': -74.60479873667268,
 'iskew_capm_21d': 5.355962619138009}